# Generated by Django 4.2.4 on 2023-08-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.BigIntegerField(null=True),
        ),
    ]
